name = "prastoot"
license = "MIT"
licenselink = "https://github.com/darshanbaral/prastoot/blob/master/LICENSE"
description = "hugo theme for making presentations"
homepage = "http://example.com/"
tags = ["presentation"]
features = ["presentation"]
min_version = "0.80.0"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
